feat: continuously update example reports (#111)
Only if it's in main branch commits, and if tests have succeeded.

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -11,11 +11,17 @@ on:
         required: false
         default: "false"
 
+permissions:
+  contents: write
+
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
 
       - name: Set up Python
         uses: actions/setup-python@v5.4.0
@@ -58,7 +64,14 @@ jobs:
         env:
           GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          pytest tests/ -v -s
+          pytest tests/ -v -s | tee output.log
+          echo "::set-output name=static_output_file::$(grep 'Static Analysis Output file path:' output.log | awk '{print $NF}')"
+          echo "::set-output name=differential_output_file::$(grep 'Differential Analysis Output file path:' output.log | awk '{print $NF}')"
+          if grep -q 'FAILURE' output.log; then
+            echo "::set-output name=status::failure"
+          else
+            echo "::set-output name=status::success"
+          fi
 
       - name: Save cache
         uses: actions/cache/save@v4.2.2
@@ -66,3 +79,20 @@ jobs:
         with:
           path: cache/
           key: dirty-waters-cache-${{ runner.os }}-${{ steps.set-sha.outputs.commit_sha }}
+
+      - name: Copy new reports to example_reports
+        if: github.ref == 'refs/heads/main' && steps.analysis.outputs.status == 'success'
+        run: |
+          cp ${{ steps.analysis.outputs.static_output_file }} example_reports/static_analysis_report_example.md
+          cp ${{ steps.analysis.outputs.differential_output_file }} example_reports/differential_analysis_report_example.md
+
+      - name: Commit reports
+        if: github.ref == 'refs/heads/main' && steps.analysis.outputs.status == 'success'
+        uses: stefanzweifel/git-auto-commit-action@v5.1.0
+        with:
+          commit_message: "chore: update example reports"
+          branch: ${{ github.head_ref }}
+
+      - name: Break the build if tests fail
+        if: steps.analysis.outputs.status == 'failure'
+        run: exit 1
